# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20160507_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reposted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
