# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_reposted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail0',
            field=models.ImageField(blank=True, null=True, upload_to='cache/'),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail1',
            field=models.ImageField(blank=True, null=True, upload_to='cache/'),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail2',
            field=models.ImageField(blank=True, null=True, upload_to='cache/'),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail3',
            field=models.ImageField(blank=True, null=True, upload_to='cache/'),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail4',
            field=models.ImageField(blank=True, null=True, upload_to='cache/'),
        ),
    ]
