# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knacks', '0012_auto_20160411_2301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_auto_20160507_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', review.models.IntegerRangeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='items.Item')),
                ('knack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knack', to='knacks.Knack')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
