# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='items.Item'),
        ),
        migrations.AlterField(
            model_name='review',
            name='knack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knack', to='knacks.Knack'),
        ),
    ]
